# NumPy

In [3]:
import numpy as np

### Array Creation

In [4]:
A = np.arange(12).reshape(4, 3)
B = np.arange(10, 70, 5).reshape(4, 3) # 10 <= x < 70. Increment by 5

print('A: \n{}\n'.format(A))
print('B: \n{}'.format(B))

A: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

B: 
[[10 15 20]
 [25 30 35]
 [40 45 50]
 [55 60 65]]


### Array Properties

In [5]:
print('A.ndim: {}\nDimension of the array (i.e., 2d array\n'.format(A.ndim))
print('A.shape: {}\n'.format(A.shape))
print('A.size: {}'.format(A.size))

A.ndim: 2
Dimension of the array (i.e., 2d array

A.shape: (4, 3)

A.size: 12


### Array Operations

In [6]:
print('A^2: \n{}\n'.format(A**2))
C = B - A
print('C = B - A: \n{}\n'.format(C))
print('C^T: \n{}\n'.format(C.T))
print('C x C^T: \n{}\n'.format(np.dot(C, C.T)))
print('a_0 . b_0: {}\n'.format(np.dot(A[0], B[0])))
print('C.sum(): {}\n'.format(C.sum()))
print('C.min(): {}\n'.format(C.min()))
print('C.max(): {}'.format(C.max()))

A^2: 
[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]

C = B - A: 
[[10 14 18]
 [22 26 30]
 [34 38 42]
 [46 50 54]]

C^T: 
[[10 22 34 46]
 [14 26 38 50]
 [18 30 42 54]]

C x C^T: 
[[ 620 1124 1628 2132]
 [1124 2060 2996 3932]
 [1628 2996 4364 5732]
 [2132 3932 5732 7532]]

a_0 . b_0: 55

C.sum(): 384

C.min(): 10

C.max(): 54


### Indexing, Slicing, Iterating

In [11]:
print('A: \n{}\n'.format(A))
print('A[0]: (first row of matrix A)\n{}\n'.format(A[0]))
print('A[:,[1]]: (second col of matrix A)\n{}\n'.format(A[:,[1]]))
print('A[0:-1]: (subset of matrix A) \n{}\n'.format(A[0:-1]))

A: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

A[0]: (first row of matrix A)
[0 1 2]

A[:,[1]]: (second col of matrix A)
[[ 1]
 [ 4]
 [ 7]
 [10]]

A[0:-1]: (subset of matrix A) 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

